In [433]:
from zipfile import BadZipFile
import librosa
import soundfile as sf
import pandas as pd
import random
from scipy.stats import skew
from sklearn import preprocessing
from sklearn.metrics import f1_score

import numpy as np
import math 
from zipfile import ZipFile
import os
from os import path
from pydub import AudioSegment
import shutil
import numpy as np
import itertools
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score  
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model
import pickle
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


## Extracting the folder names

In [434]:
folders_names=os.listdir("data")
files_name=[]
# for i in folders_names:
#     nm=os.listdir(f"folder/test")
#     files_name.append(nm)
files_name.append(folders_names)
print(folders_names)

['1c5bc995-4c9e-42db-b139-82a1260936f7.wav', '31c2ce66-7e1b-45b4-b58d-adb13f00ca7a.wav', '8211b37b-a2dd-4862-b804-e6813ee0dcaf.wav', 'a6ee5c69-85ef-4bf5-b58e-417c6a6903c8.wav', 'f638fc6a-9411-46d7-b57e-59836f9075e2.wav']


## This function takes an audio file can return its mfcc

In [435]:
def extract_features(file_name):
    import librosa
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
    mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_processed = np.mean(mfccs.T,axis=0)
     
    return mfccs_processed

## MFCC of all files with lables extracted

In [436]:
features = []

# Iterate through each sound file and extract the features 
for folder1 in folders_names:
    data = extract_features(f'data/{folder1}')
    features.append([data, folder1])#mfcc and lables

# Convert into a Panda dataframe 
featuresdf = pd.DataFrame(features, columns=['feature','class_label'])

C:\Users\HP\anaconda3\lib\site-packages\librosa\core\audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


## Lable encoding the names

In [437]:
from sklearn.preprocessing import LabelEncoder

# Convert features and corresponding classification labels into numpy arrays
X = np.array(featuresdf.feature.tolist())
# y = np.array(featuresdf.class_label.tolist())

# # Encode the classification labels
# le = LabelEncoder()
# yy = le.fit_transform(y)

In [438]:
X

array([[-3.15994781e+02,  1.34337326e+02,  1.33210258e+01,
         6.74023676e+00,  1.19348812e+00,  2.06326018e-03,
        -4.86377664e-02, -8.79075909e+00, -1.78846359e+01,
        -8.41509581e-01, -4.79962826e+00, -4.86320019e+00,
        -4.74807787e+00, -6.84414148e+00, -1.01014490e+01,
        -4.04926634e+00, -6.16196156e+00, -8.15282249e+00,
        -6.55011415e+00, -4.20095730e+00, -1.20252542e+01,
        -2.38313365e+00, -8.85501289e+00, -6.16366005e+00,
        -1.06847572e+00, -5.15698671e+00, -2.18019819e+00,
        -4.76403856e+00, -9.91168618e-01, -5.91214609e+00,
        -4.49259377e+00, -3.90762472e+00, -4.27998829e+00,
        -9.84212756e-01, -3.35846782e+00, -2.87054253e+00,
        -3.37037277e+00, -2.77407861e+00,  1.16302639e-01,
         5.81524372e-01],
       [-3.59292694e+02,  1.08881683e+02,  1.66433454e+00,
         2.20079079e+01,  1.00695992e+01,  1.55490792e+00,
        -3.00604510e+00, -4.23665476e+00, -2.05188980e+01,
        -8.32493877e+00, -8.77

## KNeighborsClassifier

In [439]:
knn = pickle.load(open("knn.pkl", 'rb'))

In [440]:
y_pred =knn.predict(X)

In [441]:
print(y_pred)

[1 1 2 1 2]


## SVM 

In [442]:
svm = pickle.load(open("svm.pkl", 'rb'))


In [443]:
#Predict the response for test dataset
y_predct = svm.predict(X)
print(y_predct)

[1 3 2 1 1]


## LogisticRegression

In [444]:
logreg =pickle.load(open("logreg.pkl", 'rb'))


In [445]:
# STEP 3: make predictions on the testing set
y_pred1 = logreg.predict(X)

print(y_pred1)


[1 3 2 1 1]


## Gaussian Naive Bayes

In [446]:
gnb = pickle.load(open("gnb.pkl", 'rb'))

y_pred22 = gnb.predict(X)
 

In [447]:
print(y_pred22)

[2 1 2 2 2]


## DecisionTreeClassifier

In [448]:

clf1 = pickle.load(open("decisiontree.pkl", 'rb'))


y_pred2 = clf1.predict(X)

In [449]:
print(y_pred2)

[1 2 2 1 1]


## GradientBoostingClassifier

In [450]:
model = pickle.load(open("GradientBoosting.pkl", 'rb'))



In [451]:
y_pred3 = model.predict(X)


In [452]:
print(y_pred3)

[1 1 1 1 2]


## RandomForestClassifier

In [453]:
clf2=pickle.load(open("RandomForest.pkl", 'rb'))
p3=clf2.predict(X)

In [454]:
print(p3)

[1 1 1 1 1]


# Results

In [455]:
labs=[0,1,2,3]
ans=['AC','light','song','tv']

In [456]:
print("KNN:",ans[y_pred[0]])
print("SVM:",ans[y_predct[0]])
print("LogisticRegression",ans[y_pred1[0]])
print("Gaussian Naive Bayes",ans[y_pred22[0]])
print("Descision tree",ans[y_pred2[0]])
print("GradientBoostingClassifier",ans[y_pred3[0]])
print("RandomForest",ans[p3[0]])

KNN: light
SVM: light
LogisticRegression light
Gaussian Naive Bayes song
Descision tree light
GradientBoostingClassifier light
RandomForest light


In [457]:
# from flask import Flask , render_template, request
# import numpy as np
# import pickle
# import joblib

# # import librosa
# # import soundfile as sf

# app = Flask(__name__)

# @app.route("/")
# def hello_world():
#     return render_template('index.html')
    


In [458]:
# if __name__ == "__main__":
#     app.run(debug=False)